version: "3"

services:
  postgres:
      restart: always
      image: postgres:10.4
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=calorie
        - POSTGRES_PASSWORD=suchSecret
        - POSTGRES_DB=cc
      volumes:
        - calorie-postgres-data:/var/lib/postgresql/data

volumes:
  calorie-postgres-data:
    external: true